#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SERVICE_NAME="techlead-observe"
RUN_USER="${SUDO_USER:-${USER}}"
TARGET_DIR="${REPO_ROOT}"
HOST="0.0.0.0"
PORT="7810"
BIN_PATH="/usr/local/bin/techlead"
UNIT_DIR="/etc/systemd/system"
ENV_DIR="/etc/default"
ENABLE_NOW=1
EXTERNAL_URL="${TECHLEAD_EXTERNAL_URL:-}"

usage() {
  cat <<USAGE
Usage:
  sudo TECHLEAD_EXTERNAL_URL=https://your-prod-domain \
    ${0##*/} [options]

Options:
  --service-name <name>   systemd service name (default: ${SERVICE_NAME})
  --user <user>           run as this linux user (default: ${RUN_USER})
  --target-dir <dir>      --dir for observe start (default: ${TARGET_DIR})
  --host <host>           observe host (default: ${HOST})
  --port <port>           observe port (default: ${PORT})
  --external-url <url>    set TECHLEAD_EXTERNAL_URL explicitly
  --bin-path <path>       install binary path (default: ${BIN_PATH})
  --unit-dir <dir>        unit file directory (default: ${UNIT_DIR})
  --env-dir <dir>         env file directory (default: ${ENV_DIR})
  --no-enable-now         only install files, don't enable/start service
  -h, --help              show this help

Notes:
  - This script builds latest binary with "zig build".
  - It writes TECHLEAD_EXTERNAL_URL to /etc/default/<service-name>.
  - If external url is empty, QR/share links will fall back to local host.
USAGE
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "error: please run as root (use sudo)." >&2
    exit 1
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --service-name)
      SERVICE_NAME="$2"
      shift 2
      ;;
    --user)
      RUN_USER="$2"
      shift 2
      ;;
    --target-dir)
      TARGET_DIR="$2"
      shift 2
      ;;
    --host)
      HOST="$2"
      shift 2
      ;;
    --port)
      PORT="$2"
      shift 2
      ;;
    --external-url)
      EXTERNAL_URL="$2"
      shift 2
      ;;
    --bin-path)
      BIN_PATH="$2"
      shift 2
      ;;
    --unit-dir)
      UNIT_DIR="$2"
      shift 2
      ;;
    --env-dir)
      ENV_DIR="$2"
      shift 2
      ;;
    --no-enable-now)
      ENABLE_NOW=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

require_root

if ! command -v zig >/dev/null 2>&1; then
  echo "error: zig is required" >&2
  exit 1
fi
if ! command -v systemctl >/dev/null 2>&1; then
  echo "error: systemctl is required" >&2
  exit 1
fi
if ! id "${RUN_USER}" >/dev/null 2>&1; then
  echo "error: user not found: ${RUN_USER}" >&2
  exit 1
fi

if [[ ! -d "${TARGET_DIR}" ]]; then
  echo "error: target dir not found: ${TARGET_DIR}" >&2
  exit 1
fi

echo "[1/6] build binary"
(
  cd "${REPO_ROOT}"
  zig build
)

mkdir -p "$(dirname "${BIN_PATH}")" "${UNIT_DIR}" "${ENV_DIR}"

echo "[2/6] install binary -> ${BIN_PATH}"
install -m 0755 "${REPO_ROOT}/zig-out/bin/techlead" "${BIN_PATH}"

UNIT_PATH="${UNIT_DIR}/${SERVICE_NAME}.service"
ENV_PATH="${ENV_DIR}/${SERVICE_NAME}"

echo "[3/6] write env -> ${ENV_PATH}"
cat > "${ENV_PATH}" <<EOF_ENV
# Generated by scripts/deploy-observe-service.sh
TECHLEAD_EXTERNAL_URL=${EXTERNAL_URL}
EOF_ENV
chmod 0644 "${ENV_PATH}"

echo "[4/6] write unit -> ${UNIT_PATH}"
cat > "${UNIT_PATH}" <<EOF_UNIT
[Unit]
Description=Techlead Observe Service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${RUN_USER}
WorkingDirectory=${TARGET_DIR}
EnvironmentFile=-${ENV_PATH}
ExecStart=${BIN_PATH} observe start --dir ${TARGET_DIR} --host ${HOST} --port ${PORT}
Restart=always
RestartSec=2
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF_UNIT
chmod 0644 "${UNIT_PATH}"

echo "[5/6] systemd reload"
systemctl daemon-reload

if [[ "${ENABLE_NOW}" -eq 1 ]]; then
  echo "[6/6] enable + restart ${SERVICE_NAME}"
  systemctl enable "${SERVICE_NAME}" >/dev/null
  systemctl restart "${SERVICE_NAME}"
  systemctl --no-pager --full status "${SERVICE_NAME}" | sed -n '1,18p'
else
  echo "[6/6] skipped enable/start (--no-enable-now)"
fi

echo
if [[ -n "${EXTERNAL_URL}" ]]; then
  echo "done: service=${SERVICE_NAME}, external_url=${EXTERNAL_URL}"
else
  echo "done: service=${SERVICE_NAME}, external_url is empty"
  echo "hint: set TECHLEAD_EXTERNAL_URL to your production domain and rerun."
fi
